# Generated by Django 2.2.3 on 2019-07-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190729_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=10, unique=True),
            preserve_default=False,
        ),
    ]
